package life.majiang.community.community.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.ID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.RECIVER
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Long reciver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.OUTERID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.TYPE
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.CREATETIME
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Long createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.STATUS
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.NOTIFIERNAME
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private String notifiername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.OUTERTITLE
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private String outertitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.QUESTIONID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    private Long questionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.ID
     *
     * @return the value of NOTIFICATION.ID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.ID
     *
     * @param id the value for NOTIFICATION.ID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.NOTIFIER
     *
     * @return the value of NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.NOTIFIER
     *
     * @param notifier the value for NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.RECIVER
     *
     * @return the value of NOTIFICATION.RECIVER
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Long getReciver() {
        return reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.RECIVER
     *
     * @param reciver the value for NOTIFICATION.RECIVER
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setReciver(Long reciver) {
        this.reciver = reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.OUTERID
     *
     * @return the value of NOTIFICATION.OUTERID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.OUTERID
     *
     * @param outerid the value for NOTIFICATION.OUTERID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.TYPE
     *
     * @return the value of NOTIFICATION.TYPE
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.TYPE
     *
     * @param type the value for NOTIFICATION.TYPE
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.CREATETIME
     *
     * @return the value of NOTIFICATION.CREATETIME
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.CREATETIME
     *
     * @param createtime the value for NOTIFICATION.CREATETIME
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.STATUS
     *
     * @return the value of NOTIFICATION.STATUS
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.STATUS
     *
     * @param status the value for NOTIFICATION.STATUS
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.NOTIFIERNAME
     *
     * @return the value of NOTIFICATION.NOTIFIERNAME
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public String getNotifiername() {
        return notifiername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.NOTIFIERNAME
     *
     * @param notifiername the value for NOTIFICATION.NOTIFIERNAME
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setNotifiername(String notifiername) {
        this.notifiername = notifiername == null ? null : notifiername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.OUTERTITLE
     *
     * @return the value of NOTIFICATION.OUTERTITLE
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public String getOutertitle() {
        return outertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.OUTERTITLE
     *
     * @param outertitle the value for NOTIFICATION.OUTERTITLE
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setOutertitle(String outertitle) {
        this.outertitle = outertitle == null ? null : outertitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.QUESTIONID
     *
     * @return the value of NOTIFICATION.QUESTIONID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public Long getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.QUESTIONID
     *
     * @param questionid the value for NOTIFICATION.QUESTIONID
     *
     * @mbg.generated Wed Dec 02 20:28:16 CST 2020
     */
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }
}